# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - jRightShoulder_rotx
      - jRightShoulder_rotz
      - jRightShoulder_roty
      - jRightElbow_rotz
      - jRightElbow_roty
      - jRightWrist_rotx
      - jRightWrist_rotz