# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - jRightShoulder_rotx
      - jRightShoulder_rotz
      - jRightShoulder_roty
      - jRightElbow_rotz
      - jRightElbow_roty
      - jRightWrist_rotx
      - jRightWrist_rotz
    command_interfaces:
      []
    state_interfaces:
      []
    allow_nonzero_velocity_at_trajectory_end: true