ee2hand:
  translation: [0.00294718, 0.02414458, 0.1025374] #y motion
  # translation: [-0.0, 0.0, 0.0] # no motion
  rotation: [-0.5511851645887941, 0.3996510340664562, 0.7312376526605968, -0.04201738495261773] # y motion

  # translation: [-0.0192054 , -0.01007333, 0.07440475] #z motion
  # rotation: [-0.5890074234509467, 0.2732182596988888, 0.7587816627860343, 0.05169551147293741] # z motion


operational:
    method: "NLopt"  # Method to use for optimization, e.g., "SVD", "Levenberg-Marquardt"

    print_error_before_loop: false  # Print error before optimization loop
    print_error_in_loop: false  # Print error after optimization loop
    print_error_after_loop: true  # Print error after optimization loop
    print_joint_angles: false  # Print joint angles during optimization

    baseline_hz: 20  # Baseline frequency for optimization
NLopt:
  algorithm: "LN_COBYLA"  # Optimization algorithm to use, e.g., "LD_LBFGS", "LN_COBYLA"
  max_iterations: 300  # Maximum iterations for NLopt
  tolerance: 1e-3  # Tolerance for convergence
  pos_weight: 7.0  # Weight for position error in cost function
  rot_weight: 3.0  # Weight for rotation error in cost function
  joint_weights: [1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0]  # Weights for joint angles
  joint_penalty_weight: 0.7  # Penalty weight for joint angles
  acceleration_weight: 0.1  # Weight for acceleration in cost function
  velocity_weight: 0.1  # Weight for velocity in cost function

SVD:
  max_iterations: 100  # Maximum iterations for SVD
  convergence_threshold: 1e-2  # Threshold for convergence
  damping_factor: 0.1  # Damping factor for optimization
  print_jacobian: false  # Print Jacobian matrix during optimization

# initial_joint_states: [-1.8662461835704307, 0.8590559575694462, -0.6697032662556018, 0.21030423026992587, 0.0, 0.0, 0.0]
initial_joint_states: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # Initial joint states for the arm


sensitivity_analysis:
    apply_sensitivity: true  # Whether to apply sensitivity analysis
    sigma: 0.2
