ee2hand:
  translation: [0.0,-0.03,0.08] #y motion
  # x y z w
  rotation: [0.5, 0.5, -0.5, 0.5]

arm_geometry:

# subject 0
  upper_arm_length: 0.35
  forearm_length: 0.26





operational:
    method: "NLopt"  # Method to use for optimization, e.g., "SVD", "Levenberg-Marquardt"

    print_error_before_loop: false  # Print error before optimization loop
    print_error_in_loop: false  # Print error after optimization loop
    print_error_after_loop: false  # Print error after optimization loop
    print_joint_angles: false  # Print joint angles during optimization
    print_critical_transforms: false  # Print critical transforms during optimization

    baseline_hz: 20  # Baseline frequency for optimization
NLopt:
  algorithm: "LN_COBYLA"  # Optimization algorithm to use, e.g., "LD_LBFGS", "LN_COBYLA"
  max_iterations: 300  # Maximum iterations for NLopt
  tolerance: 1e-3  # Tolerance for convergence
  pos_weight: 7.0  # Weight for position error in cost function
  rot_weight: 3.0  # Weight for rotation error in cost function
  joint_weights: [1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0]  # Weights for joint angles
  joint_penalty_weight: 0.7  # Penalty weight for joint angles
  acceleration_weight: 0.1  # Weight for acceleration in cost function
  velocity_weight: 0.1  # Weight for velocity in cost function

# initial_joint_states: [-1.8662461835704307, 0.8590559575694462, -0.6697032662556018, 0.21030423026992587, 0.0, 0.0, 0.0]
initial_joint_states: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # Initial joint states for the arm


sensitivity_analysis:
    apply_sensitivity: false  # Whether to apply sensitivity analysis
    sigma: 0.1


velocity_estimation:
  use_kalman_filter: true  # Whether to use Kalman Filter for velocity estimation
  timing:
    tf_lookup_timeout_sec: 0.05
    fallback_to_latest_tf: true
  # ===== Core KF (state x = [q, dq]) =====
  kf:
    q_q: 1.0          #  trust in initial joint positions (rad^2 per tick)
    q_dq: 1.0             # trust in initial joint velocities ((rad/s)^2 per tick)
    q_a: 1.0e-3             # process noise
    velocity_decay: 1.0     # s^-1, pulls predicted joint velocity back toward zero

    control_rate_hz: 250.0  # used to set KF dt (fallback if timestamp deltas look bad)

    r_sigma_lin: 0.01
    r_sigma_rot: 0.01
    sigma_q: 0.1
    sigma_dq: 0.5

    acc_cap: 50.0  # cap on max acceleration (rad/s^2)

  # ===== Outputs =====
  output:
    print_velocity: true  # print joint velocities to console
    print_sigmas: false  # print measurement and task sigmas to console
    print_arm_joint_velocities: false  # print estimated arm joint velocities to console
