ee2hand:
  translation: [0.0, -0.026, 0.07]  # x, y, z in meters
  rotation: [3.14, 0, -1.57]  # Roll, Pitch, Yaw in radians

world2camera:
  translation: [-0.1,-0.45,0.09]  # x, y, z in meters
  rotation: [-1.57,0.0,-1.57]  # Roll, Pitch, Yaw in radians

operational:
    method: "SVD"  # Method to use for optimization, e.g., "SVD", "Levenberg-Marquardt"
    
    print_error_before_loop: false  # Print error before optimization loop
    print_error_in_loop: false  # Print error after optimization loop
    print_error_after_loop: false  # Print error after optimization loop
    print_jacobian: false  # Print Jacobian matrix during optimization

    max_iterations: 100  # Maximum number of iterations for optimization
    convergence_threshold: 1e-2  # Threshold for convergence
    damping_factor: 0.1  # Damping factor for optimization

    baseline_hz: 20  # Baseline frequency for optimization

initial_joint_states: [-1.8662461835704307, 0.8590559575694462, -0.6697032662556018, 0.21030423026992587, 0.0, 0.0, 0.0]
# initial_joint_states: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # Initial joint states for the arm
  