parameters:
  # ===== Core KF (state x = [q, dq]) =====
  kf:
    q_q: 1.0e-3            # process noise on q   (rad/s)^2 per tick
    q_dq: 1.0e-1             # process noise on dq  (rad/s^2)^2 per tick
    q_a: 0.0001             # process noise on acceleration (rad/s^3)^2 per tick

    control_rate_hz: 200.0  # used to set KF dt (fallback if timestamp deltas look bad)

    sigma_task: 0.5
    sigma_null: 2.0

    r_sigma_lin: 0.02
    r_sigma_rot: 0.05
    sigma_q: 0.05
    sigma_dq: 0.3

    acc_cap: 10.0  # cap on max acceleration (rad/s^2)

  # ===== Outputs =====
  output:
    print_velocity: false  # print joint velocities to console
    print_sigmas: false  # print measurement and task sigmas to console
    print_arm_joint_velocities: false  # print estimated arm joint velocities to console

  visualizer:
    static_transformation: [-0.075, -0.35, 0.09, -0.5, 0.5, -0.5, 0.5]  # x, y, z, qx, qy, qz, qw